name: Run Python Tests
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          python setup.py install
      - name: Run tests with pytest
        run: |
          cd fast_form/tests
          export PYTHONPATH=../
          python -m unittest discover -s . -t .